          backend:
            name: git-gateway
            branch: main # <-- We may need to change this!

          media_folder: "public/uploads"

          # We will configure this later, after the login works.
          collections: []