                    # This tells the CMS to use test-repo backend for development (no authentication required)
                    backend:
                      name: test-repo

                    # This tells the CMS where to save any images you upload.
                    media_folder: "client/public/uploads"
                    public_folder: "/uploads"

                    # This is where we define the content you can edit.
                    # We will start by adding your French translation file here.
                    collections:
                      - name: "translations" # An internal name for this content type
                        label: "Website Content (French)" # The name you will see in the CMS
                        files:
                          - label: "French Translations"
                            name: "fr_translations"
                            file: "client/public/locales/fr/translation.json" # The exact path to your file
                            fields:
                              # We need to add fields that match your JSON file structure.
                              # For now, let's just add one simple field as a test.
                              - { label: "Test Field", name: "test_field", widget: "string" }